## ----------------------------------------------------------------------------
## nexus | pde.config.mac
##
## Configuration macro to simulate the proof of principle of a photon detection efficiency for 
## wavelength shifting fibres.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/control/execute macros/generators/SingleParticle.mac

/control/execute macros/physics/IonizationElectron.mac

/nexus/persistency/output_file outputs/TotalTrackLength_ex/trial.next
